# Generated by Django 4.0.5 on 2022-06-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caskanje',
            fields=[
                ('idcaskanje', models.AutoField(db_column='idCaskanje', primary_key=True, serialize=False)),
                ('smer', models.CharField(max_length=1)),
                ('datum_vreme', models.DateTimeField()),
                ('poruka', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'caskanje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Komentari',
            fields=[
                ('idkomentari', models.AutoField(db_column='idKomentari', primary_key=True, serialize=False)),
                ('smer', models.CharField(max_length=1)),
                ('komentar', models.CharField(max_length=255)),
                ('datum_vreme', models.DateTimeField()),
            ],
            options={
                'db_table': 'komentari',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('idkorisnik', models.AutoField(db_column='idKorisnik', primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=45)),
                ('prezime', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('pol', models.CharField(max_length=1)),
                ('sifra', models.CharField(max_length=45)),
                ('grad', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('telefon', models.CharField(max_length=45)),
                ('opis', models.CharField(blank=True, db_column='Opis', max_length=255, null=True)),
                ('slika', models.ImageField(upload_to='korisnici_img')),
                ('status', models.CharField(max_length=1)),
                ('datum_ban', models.DateField(blank=True, null=True)),
                ('ocena', models.IntegerField(blank=True, null=True)),
                ('br_ocena', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'korisnik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saradnja',
            fields=[
                ('idsaradnja', models.AutoField(db_column='idSaradnja', primary_key=True, serialize=False)),
                ('datum', models.DateField()),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'saradnja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zanatlija',
            fields=[
                ('idzanatlija', models.AutoField(db_column='idZanatlija', primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=45)),
                ('prezime', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('pol', models.CharField(max_length=1)),
                ('sifra', models.CharField(max_length=45)),
                ('grad', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('telefon', models.CharField(max_length=45)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
                ('slika', models.ImageField(upload_to='zanatlije_img')),
                ('zanati', models.CharField(max_length=255)),
                ('ime_firme', models.CharField(max_length=45)),
                ('adresa_lokala', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=1)),
                ('datum_ban', models.DateField(blank=True, null=True)),
                ('ocena', models.IntegerField(blank=True, null=True)),
                ('br_ocena', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zanatlija',
                'managed': False,
            },
        ),
    ]
