# Generated by Django 4.0.5 on 2022-06-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZanatlijeApp', '0002_delete_saradnja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocene',
            fields=[
                ('idocene', models.AutoField(primary_key=True, serialize=False)),
                ('ocena', models.IntegerField()),
            ],
            options={
                'db_table': 'ocene',
                'managed': False,
            },
        ),
    ]
